language: node_js
node_js:
  - "11.12.0"

branches:
  only:
    - master

before_script:
  - yarn add -g firebase-tools
  - yarn add -g wintersmith

script:
  - wintersmith build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}